### ISSUE TITLE
Why app.get('/profile' ? Why /profile page at all?

### ISSUE THREAD

**Issue by wzup** [scotch-io/easy-node-authentication#32]
I wonder why do you make so inconvenient design? 
Do FB, Amazon, Ebay, any modern sites have some special dedicated pages to get you to your profile?
If you were loged in, you just follow `facebook.com` (not `facebook.com/profile` or smth !!) and simply get to your members restricted area.
Why do you make up some useless `/profile` routes?

**Comment by mbt-jeremy-r** [comment]
@wzup : Because it isn't meant to be a full fledged website like facebook, but a example app to understand Passport and OAuth. And `/profile` is meant to show you the differents key from fb, github... so that you can try and experiment.
And since the example show you how to handle different cases on auth fail, you can easily render a different page on `/` depending of the status of the user.

**Comment by sevilayha** [comment]
@mbt-jeremy-r is totally correct. demo app for learning. switch out routes for your own applications as you see fit.
